version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet build .\src\GradeBook --configuration Release --no-restore
  - cmd: dotnet test .\test\GradeBook.Tests --configuration Release --no-restore
after_build:
  # For once the build has completed
clone_depth: 1
on_finish :
  # any cleanup in here
deploy: off