code --install-extension adisreyaj.sonarqube-status
code --install-extension bibhasdn.git-easy
code --install-extension dareenzo.theme-inspired-github
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension FelschR.extbundles-csharp
code --install-extension formulahendry.dotnet
code --install-extension henriqueBruno.github-repository-manager
code --install-extension k--kato.docomment
code --install-extension KishoreIthadi.dotnet-core-essentials
code --install-extension KnisterPeter.vscode-github
code --install-extension leo-labs.dotnet
code --install-extension Leopotam.csharpfixformat
code --install-extension maurobussini.vscode-dotnet-essentials
code --install-extension mavis.csharpextensions
code --install-extension mfery.dotnetexplorer
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-azureappservice
code --install-extension ms-azuretools.vscode-azurefunctions
code --install-extension ms-azuretools.vscode-azurestorage
code --install-extension ms-azuretools.vscode-cosmosdb
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.azurecli
code --install-extension niudai.remote-github
code --install-extension nurlybekovnt.csharpextensions
code --install-extension pflannery.vscode-versionlens
code --install-extension piotrpalarz.vscode-gitignore-generator
code --install-extension qp.csharp-workspace
code --install-extension roadsidejesus.csharp-helper
code --install-extension SonarSource.sonarlint-vscode
code --install-extension stuartleaver.dotnet-azure-extensionpack
code --install-extension sysoev.vscode-open-in-github
code --install-extension tintoy.msbuild-project-tools
